---
# defaults file for mpd

mpd_autostart: true
mpd_install_mpc: true
mpd_install_ncmpcpp: true
mpd_ncmpcpp_mpd_host: localhost

# ATTENTION!
# OS-Specific variables can be found in vars/ directory of this role
#
mpd_port: 6600
mpd_bind_to_address: any
mpd_name: Music Player Daemon
mpd_restore_paused: true
mpd_auto_update: true
mpd_follow_inside_symlinks: true
mpd_follow_outside_symlinks: false
mpd_users:
  - "{{ ansible_user_id }}"
  - root

# Add your OS-Specific outputs here depending on your hardware drivers:
#
mpd_outputs:
  - name: "FIFO_Visualizer"
    type: "fifo"
    path: "/tmp/mpd.fifo"
    format: "44100:16:2"
  - name: MyRadio
    type: httpd
    port: 8080
    encoder: lame
    always_on: 'yes'
    replay_gain_handler: software
    replaygain: track
    replaygain_preamp: 0
    volume_normalization: 'yes'
    tags: 'yes'
    bitrate: 64
    format: 22050:16:1
