---
- name: "[main] Include {{ ansible_os_family }}-specific variables"
  ansible.builtin.include_vars: "{{ ansible_system|lower }}.yml"
  tags: tmux

- name: "[main] Include OS-specific installation tasks"
  ansible.builtin.include_tasks: "{{ ansible_system|lower }}.yml"
  tags: tmux

- name: "[main] Import Configuration tasks"
  ansible.builtin.import_tasks: config.yml
  tags: tmux
